### PR TITLE
doc: ncu-team sync update

### PR DESCRIPTION
**Pull request by BethGriggs**
`ncu-team sync README.md`

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by ljharb** [comment]
seems like maybe the release team isn't on the access list for this repo. should it be?

**Comment by BethGriggs** [comment]
>  seems like maybe the release team isn't on the access list for this repo. should it be?

Oh hmm, it looks like CITGM GitHub team is not a subteam of the parent Release WG team. I cannot remember if that was always the case or the team structure got changed at some point.

Not sure whether we should make it a subteam, or just grant the CITGM team access to this repository also.

**Comment by ljharb** [comment]
subteams get all the access their parent teams have, so it'd be more like, citgm was a parent of release - which probably doesn't make sense.

so i'd assume adding the citgm team specifically would make the most sense

**Comment by richardlau** [comment]
Why would the CITGM team need access to the release repository?

**Comment by ljharb** [comment]
@richardlau perhaps they don't. but this repo's readme lists the citgm team, and my approval here was gray instead of green.

¯\\\_(ツ)_/¯ just bringing it up, no strong feelings here

**Comment by BethGriggs** [comment]
@ljharb it's a fair comment to raise - conceptually we have, and our wording implies, that the CITGM team is a subteam of the wider-Release WG and all other subteams of release have write access. If CITGM is an exception then we should be clear why.

> Why would the CITGM team need access to the release repository?

At least to maintain their list of members. It's reasonable to  decide not to grant access, but then maybe the member list for CITGM should be listed in a place where the team has access to review it.

**Comment by Trott** [comment]
> @richardlau perhaps they don't. but this repo's readme lists the citgm team, and my approval here was gray instead of green.
> 
> ¯\_(ツ)_/¯ just bringing it up, no strong feelings here

CITGM was removed as a subteam from Release based on the conversations in https://github.com/nodejs/admin/issues/737. As such, the thing to do is probably to move the CITGM members list to the CITGM repository.

**Comment by BethGriggs** [comment]
Updated based on https://github.com/nodejs/citgm/pull/944

**Review by richardlau — APPROVED** [review]

**Review by targos — APPROVED** [review]

**Pull request merged**
