### PR TITLE
schedule: adjust Node.js 16 End-of-Life

### PR DESCRIPTION
**Pull request by richardlau**
Update schedule, README table and chart to reflect the change to
Node.js 16's End-of-Life date to September 11, 2023.

Move Node.js 17 to End-of-Life table.

Refs: https://github.com/nodejs/TSC/issues/1222
Refs: https://github.com/nodejs/nodejs.org/pull/4629

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by arhart** [comment]
@richardlau I'm glad to see this merged. I see the updated graphic at https://nodejs.org/en/about/releases/, but the table text still says 2024-04-30. Is there another location that needs updated, or is there just some sort of propagation delay to be waited out?

**Comment by richardlau** [comment]
@arhart I think the website downloads the schedule at build time (https://github.com/nodejs/nodejs.org/blob/eaeb684633ba3d1a939bbe0d6c459855bb214e72/package.json#L14) so the next time the website is rebuilt (e.g. when another pr is merged to https://github.com/nodejs/nodejs.org) the table will be automatically rebuilt.

**Comment by nschonni** [comment]
I landed a Dependabot PR so the site should have rebuilt now

**Pull request merged**
