### PR TITLE
update schedule image

### PR DESCRIPTION
**Pull request by cjihrig**

### CODE REVIEW

**Comment by gibfahn** [comment]
I note that the new image is 960x500 rather than 2666x

**Comment by cjihrig** [comment]
FWIW, the lts module also outputs SVG if you want something more scalable.

**Comment by MylesBorins** [comment]
Would it be possible to include documentation as to how you updated the
image in this pr?

**Comment by cjihrig** [comment]
@MylesBorins any suggestions on where those instructions would go? I don't really want to add it to the README, as I'd rather keep that document focused.

**Comment by MylesBorins** [comment]
Could it be in the readme of the module, and just have a note below the image

**Comment by cjihrig** [comment]
Sure. I added a link to the module's npm page here. That page already contains docs for how to use it, and the various supported options.

**Pull request merged**
