### PR TITLE
doc: add @ruyadorno to releasers

### PR DESCRIPTION
**Pull request by richardlau**
Synced README.md with `ncu-team sync README.md`.

### CODE REVIEW

**Comment by nschonni** [comment]
Should this also be in sync with people that have release keys https://github.com/nodejs/node/#release-keys

**Comment by richardlau** [comment]
> 
> 
> Should this also be in sync with people that have release keys https://github.com/nodejs/node/#release-keys

@ruyadorno Friendly reminder to PR your GPG key into the Node.js readme and docker-node as per https://github.com/nodejs/Release/blob/master/GOVERNANCE.md#adding-new-releasers

**Comment by ruyadorno** [comment]
@richardlau completed all the steps there 😊 thanks for the reminder!

**Comment by MylesBorins** [comment]
GPG key has landed on master and PR is open for docker... landing this

**Pull request merged**
