### PR TITLE
schedule: update graphic timeline

### PR DESCRIPTION
**Pull request by targos**
```
npx lts --start 2024-06-15 --end 2026-07-15 -d "$PWD/schedule.json" -g "$PWD/schedule.svg"
npx svgo "$PWD/schedule.svg"
```

### CODE REVIEW

**Comment by targos** [comment]
I could extend the end date, but I think it's more readable now and two years should be enough.

**Review by richardlau — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]

**Review by UlisesGascon — APPROVED** [review]
LGTM!

**Comment by targos** [comment]
Just looked at the diff again and realized that `master` is back.

**Comment by richardlau** [comment]
> Just looked at the diff again and realized that `master` is back.

Maybe we need to merge https://github.com/nodejs/lts-schedule/pull/15?

**Comment by targos** [comment]
Merged, released, and updated the svg

**Review by richardlau — APPROVED** [review]

**Pull request merged**
