### PR TITLE
doc: mark v14.x as End-of-Life

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
Was it a scheduled PR? :smile:

**Comment by targos** [comment]
Not at all.

**Review by richardlau — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by Jb6422** [comment]
> Was it a scheduled PR? :smile: 

https://worksheets.codalab.org/rest/bundles/0xadf98bb30a99476ab56ebff3e462d4fa/contents/blob/glove.6B.100d.txt-vocab.txtqir1a

**Review by BethGriggs — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@targos 
> Feel free to open a PR, but I think it's nice to keep it in the image for some time (so people can see when support ended)

Understood! No, in that case it's fine.

**Pull request merged**
