### PR TITLE
Added License to project

### PR DESCRIPTION
**Pull request by jivthesh**

### CODE REVIEW

**Comment by mhdawson** [comment]
@jivthesh not sure what your question is. If it is whether you could use the text from the link I provided instead of the text in the Pr then yes with updates to reflect the Release repository versus the package-maintenance one.

**Comment by AbhipsaGuru1012** [comment]
Can I work on this issue?

**Comment by jivthesh** [comment]
@mhdawson ok i will make changes

**Comment by BethGriggs** [comment]
Closing as this hasn't been updated in a while. @jivthesh just let us know if you wish to pick this up again and we can reopen 🙂

**Pull request closed without merging**
