### PR TITLE
 schedule: update graphic, add dates for Node.js 19 and 20

### PR DESCRIPTION
**Pull request by BethGriggs**

### CODE REVIEW

**Review by cjihrig — APPROVED** [review]

**Comment by richardlau** [comment]
Was the graphic generated before the schedule was updated? Node.js 19 and 20 are not showing on it.

**Comment by BethGriggs** [comment]
> Was the graphic generated before the schedule was updated? Node.js 19 and 20 are not showing on it.

Aware - that was intentional. Adding those to the image before the removal of Node.js 12 I think makes the timeline harder to read/follow.  Showing the 7 release lines at once just doesn't seem ideal:

schedule

**Comment by BethGriggs** [comment]
To add, I tried modifying the dates earlier to cut off Node.js 20 - but any shorter windows it ends up rendering awkwardly:

image

**Review by richardlau — APPROVED** [review]

**Comment by Nixinova** [comment]
> I think makes the timeline harder to read/follow. Showing the 7 release lines at once just doesn't seem ideal:

That graph looks fine enough in my opinion.

**Pull request merged**
