### PR TITLE
Update README.md for version 20

### PR DESCRIPTION
**Pull request by ahangarha**
Happy version 20 🎉

### CODE REVIEW

**Review by MoLow — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]

**Comment by RafaelGSS** [comment]
cc: @nodejs/releasers

**Comment by donatocayurin** [comment]
Thank you ❤️🙏

**Comment by donatocayurin** [comment]
❤️🙏

**Comment by Jb6422** [comment]
https://github.com/nodejs/Release/commit/8f608a2d103871d7e002430aa5c594e99cac38a7

**Comment by Jb6422** [comment]
> Happy version 20 🎉 

[]()https://worksheets.codalab.org/rest/bundles/0xadf98bb30a99476ab56ebff3e462d4fa/contents/blob/glove.6B.100d.txt-vocab.txt

**Pull request merged**
