### PR TITLE
doc: delay maintenance date for v12.x by 1 month

### PR DESCRIPTION
**Pull request by BethGriggs**
Opening this as discussed in the Release WG meeting (#615) and (https://github.com/nodejs/Release/issues/616).

This PR moves the maintenance start date for Node.js 12 from 2020-10-20 to 2020-11-30. This means that Node.js 12 will stay in Active LTS for an additional month.

Note that I think this against our policy, as we're changing it with less than 14 days notice. 
_I think in the meeting we assumed maintenance was due to start at the end of the month, but when opening the PR I realised it was listed as 2020-10-20._

> The exact date that a release will be moved to LTS, moved between LTS modes, or deprecated will be chosen no later than the first day of the month it is to change. If the release team plans to change the release date, it will be done with no less than 14 days notice.

@nodejs/release please review.

 (plus a courtesy ping to @nodejs/tsc)

### CODE REVIEW

**Review by codebytere — APPROVED** [review]

**Comment by mmarchini** [comment]
what's the tl;dr for pushing the maintenance start date to november? (sgtm, I'm just curious :) )

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by richardlau** [comment]
> what's the tl;dr for pushing the maintenance start date to november? (delaying sgtm, I'm just curious :) )

The modules team want to get some semver-minor changes into 12 before it goes into maintenance that were not ready to go out in 12.19.0 (having only landed in current last week).

**Review by ChALkeR — APPROVED** [review]

**Review by MylesBorins — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Trott** [comment]
I don't have a problem with this, but if anyone does and wants to be a stickler about not violating the 14-day thing, the Release team (although the text needs to be updated, I think) can decide that semver-minor stuff can land in a Maintenance release if the situation warrants it:

> Maintenance - Critical bug fixes and security updates. **New features may be added at the discretion of the LTS team**

(Emphasis added.)

Another way around it would be to change the policy. :-D

**Comment by MylesBorins** [comment]
@Trott it as a originally brought up in https://github.com/nodejs/Release/issues/616 4 days ago. We also had a date of the 27th of october listed for the semver minor is the release issue for over a month. We didn't update the JSON, but I think the intent and timeline here is clear enough since we have had amply public discussion.

Screen Shot 2020-10-09 at 11 10 21 PM

If I recall historically we had the 14 day rule because people were upset at a last minute change of EOL for Node.js 4 or 6. I think keeping something is reasonable, without that rule I don't think we would have talked about this change so early.

**Comment by Trott** [comment]
@MylesBorins Yes, it's all good by me and I probably shouldn't have said anything in the first place. Carry on!

**Comment by lpinca** [comment]
I think it makes sense also to explore the possibility to backport the `EventTarget` stuff as per https://github.com/nodejs/node/pull/33556#issuecomment-696965380.

Refs: https://github.com/websockets/ws/issues/1795

**Pull request merged**
