### PR TITLE
doc: sync team membership (remove rvagg, add jasnell)

### PR DESCRIPTION
**Pull request by rvagg**
removing myself from this team, it's been a good ride but I'm dead weight at this point and I'm happy to see there's energy in here for doing this work

`ncu-team` has added @jasnell during the edit, I presume that's a correct reflection of the team.

### CODE REVIEW

**Comment by richardlau** [comment]
> `ncu-team` has added @jasnell during the edit, I presume that's a correct reflection of the team.

James said in https://github.com/nodejs/Release/pull/412#issuecomment-458404066 that he's emeritus in the LTS team.

**Comment by jasnell** [comment]
I am active in the release team. Inactive in lts.

**Comment by rvagg** [comment]
@jasnell the "release" team is just a parent of citgm, lts and releasers and has no members itself. This repo used to be "LTS" but its team was never renamed when the repo was, so we have a discrepancy now. You're a member of nodejs/lts, nodejs/backporters and nodejs/releasers. ncu-team has got the sync right, so maybe you want to revisit what teams you're a member of?

**Comment by jasnell** [comment]
Of the three I should only be a member of nodejs/releasers

**Comment by rvagg** [comment]
done, in the actual teams and here too

**Pull request closed without merging**
